### ISSUE TITLE
[Design] 디자인 수정입니다

### ISSUE THREAD

**Issue by taejun0** [taejun0/2024_udongchin_front#21]
## ✔️ Issue

디자인 수정 1차 진행했습니다.
어색한 부분 및 애니메이션 추가했어요.

## 📝 To-do

- [x] 서브메뉴 디자인 요소 넣기
- [x] 복수 이미지 Crop 안하고 한 번에 올리기.
- [x] 홈페이지 스타일링
- [x] 오른쪽 위 X 버튼이 안 눌리는 경우 에러 발생

- [x] 제보페이지 지도

- [x] #34
- [x] 내 거리상 존재하는 애들만 볼 수 있도록
- [x] 내가 올린 것들만 지도에서 볼수 있도록

## 🛠 Working time

3D
