### ISSUE TITLE
Design: 디자인 수정 요청사항 해결

### ISSUE THREAD

**Issue by taejun0** [taejun0/2024_udongchin_front#40]
## ✔️ Issue

Figma final 상의 모달창을 구현한다.

## 📝 To-do

- [x] 내 우동친 기록 디자인 수정
- [x] 디테일 모달 폰트 및 디자인 수정
- [x] 제보 페이지 위치 정보 디자인 수정

## 🛠 Working time

1D
