### ISSUE TITLE
[Feature] API 연결

### ISSUE THREAD

**Issue by taejun0** [taejun0/2024_udongchin_front#46]
## ✔️ Issue

figma에 따라 만든 UI에 API를 연결한다.

## 📝 To-do

- [x] #47
- [x] 지도 디테일 API 연결 & 긴급 전환 API 연결 & 좋아요 API 연결
- [ ] 제보 페이지 API 연결
- [ ] 내 우동친 기록 API 연결

## 🛠 Working time

2 Days
